// Generated by CoffeeScript 1.12.2
var Ractive, RactiveCompiler, sysPath, umd;

Ractive = require('ractive');

sysPath = require('path');

umd = require('umd-wrapper');

module.exports = RactiveCompiler = (function() {
  RactiveCompiler.prototype.brunchPlugin = true;

  RactiveCompiler.prototype.type = 'template';

  RactiveCompiler.prototype.extension = 'rac';

  RactiveCompiler.prototype.pattern = /\.(?:rac|ractive)$/;

  function RactiveCompiler(config) {
    this.config = config;
    null;
  }

  RactiveCompiler.prototype.compile = function(data, path, callback) {
    var err, error, result;
    try {
      return result = umd(JSON.stringify(Ractive.parse(data)));
    } catch (error1) {
      err = error1;
      return error = err;
    } finally {
      callback(error, result);
    }
  };

  RactiveCompiler.prototype.include = [sysPath.join(sysPath.parse(require.resolve('ractive')).dir, 'ractive.runtime.js')];

  return RactiveCompiler;

})();
